"""initial schema

Revision ID: 3b18e57171af
Revises: 
Create Date: 2026-04-09 16:51:50.236508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b18e57171af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=True),
    sa.Column('energy_consumption', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recorded_at', name='uq_activity_recorded_at')
    )
    op.create_index(op.f('ix_activity_recorded_at'), 'activity', ['recorded_at'], unique=False)
    op.create_table('recovery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('stress_state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recorded_at', name='uq_recovery_recorded_at')
    )
    op.create_index(op.f('ix_recovery_recorded_at'), 'recovery', ['recorded_at'], unique=False)
    op.create_table('sleep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sleep_id', sa.String(), nullable=True),
    sa.Column('deep_duration', sa.Integer(), nullable=True),
    sa.Column('light_duration', sa.Integer(), nullable=True),
    sa.Column('rem_duration', sa.Integer(), nullable=True),
    sa.Column('hr_avg', sa.Integer(), nullable=True),
    sa.Column('hr_min', sa.Integer(), nullable=True),
    sa.Column('hrv', sa.Float(), nullable=True),
    sa.Column('spo2_avg', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recorded_at', name='uq_sleep_recorded_at')
    )
    op.create_index(op.f('ix_sleep_recorded_at'), 'sleep', ['recorded_at'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sport_type', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('total_ascent', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('hr_avg', sa.Integer(), nullable=True),
    sa.Column('hr_max', sa.Integer(), nullable=True),
    sa.Column('hr_min', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file')
    )
    op.create_index(op.f('ix_workouts_recorded_at'), 'workouts', ['recorded_at'], unique=False)
    op.create_table('sleep_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sleep_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sleep_id'], ['sleep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_stages_sleep_id'), 'sleep_stages', ['sleep_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleep_stages_sleep_id'), table_name='sleep_stages')
    op.drop_table('sleep_stages')
    op.drop_index(op.f('ix_workouts_recorded_at'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_sleep_recorded_at'), table_name='sleep')
    op.drop_table('sleep')
    op.drop_index(op.f('ix_recovery_recorded_at'), table_name='recovery')
    op.drop_table('recovery')
    op.drop_index(op.f('ix_activity_recorded_at'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
