"""add hr zones to workouts

Revision ID: 764152f072c2
Revises: 3b18e57171af
Create Date: 2026-04-09 16:56:26.650071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764152f072c2'
down_revision: Union[str, None] = '3b18e57171af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('hr_zone_1', sa.Float(), nullable=True))
    op.add_column('workouts', sa.Column('hr_zone_2', sa.Float(), nullable=True))
    op.add_column('workouts', sa.Column('hr_zone_3', sa.Float(), nullable=True))
    op.add_column('workouts', sa.Column('hr_zone_4', sa.Float(), nullable=True))
    op.add_column('workouts', sa.Column('hr_zone_5', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'hr_zone_5')
    op.drop_column('workouts', 'hr_zone_4')
    op.drop_column('workouts', 'hr_zone_3')
    op.drop_column('workouts', 'hr_zone_2')
    op.drop_column('workouts', 'hr_zone_1')
    # ### end Alembic commands ###
